version: 2
updates:
  # Dependabot for Rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dependabot for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dependabot for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
