[package]
name = "ecc"
version = "0.1.0"
edition = "2021"

[lib]
name = "client"
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.6"
pyo3 = { version = "0.23.3", features = ["extension-module"] }
rand = "0.9.0"
thiserror = "2.0.11"
