from typing import Optional

class PyCurve:
    def __init__(self, a: int, b: int, prime: int) -> None: ...
    def point(self, x: int, y: int) -> PyPoint: ...
    @property
    def a(self) -> int: ...
    @property
    def b(self) -> int: ...
    @property
    def prime(self) -> int: ...

class PyPoint:
    @property
    def x(self) -> Optional[int]: ...
    @property
    def y(self) -> Optional[int]: ...
    def __eq__(self, other: PyPoint) -> bool: ...
