name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8

      - name: Cache mise
        uses: actions/cache@v4
        with:
          path: ~/.local/share/mise
          key: ${{ runner.os }}-mise-${{ hashFiles('**/mise.toml') }}
          restore-keys: |
            ${{ runner.os }}-mise-

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  check:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        task: [test, lint]
        include:
          - task: test
            command: cargo make ci
          - task: lint
            command: cargo make check-python
    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8

      - name: Set up Python
        run: mise i

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Restore mise cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.local/share/mise
          key: ${{ runner.os }}-mise-${{ hashFiles('**/mise.toml') }}

      - name: Restore Rust cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Restore Python cache
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}

      - name: Run ${{ matrix.task }}
        run: ${{ matrix.command }}
